fullname = input ("Enter your name:")
address = input ("Enter your address:")
birthday = input ("When is your birthday:")
college = input ("Enter your college:")
course = input ("Enter your course:")
year = input ("Enter your year:")
section = input ("Enter your section:")
hobbies = input ("Enter your hobbies:")

print ("")
print ("My name is", fullname)
print ("Im from", address)
print ("My Birthday is on", birthday)
print ("My college, " + str (college) + " course, " + str (course) + " year, " + str (year) + " and section ",section)
print ("My Hobbies are", hobbies)
